<a href="https://colab.research.google.com/github/yashsj/ML_Python/blob/master/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pwd

'/content'

In [2]:
cd ..

/


In [3]:
ls

bin/      datalab/  home/   lib64/  opt/   run/   sys/                tools/
boot/     dev/      lib/    media/  proc/  sbin/  tensorflow-1.15.2/  usr/
content/  etc/      lib32/  mnt/    root/  srv/   tmp/                var/


In [4]:
cd home

/home


In [5]:
ls

In [6]:
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd

Saving airfoil_self_noise.dat to airfoil_self_noise.dat


In [7]:
from __future__ import print_function, division

In [8]:
from future.utils import iteritems

In [9]:
from builtins import range, input

In [10]:
df=pd.read_csv('airfoil_self_noise.dat',sep='\t',header=None)

In [11]:
df

0     1       2     3         4        5
0      800   0.0  0.3048  71.3  0.002663  126.201
1     1000   0.0  0.3048  71.3  0.002663  125.201
2     1250   0.0  0.3048  71.3  0.002663  125.951
3     1600   0.0  0.3048  71.3  0.002663  127.591
4     2000   0.0  0.3048  71.3  0.002663  127.461
...    ...   ...     ...   ...       ...      ...
1498  2500  15.6  0.1016  39.6  0.052849  110.264
1499  3150  15.6  0.1016  39.6  0.052849  109.254
1500  4000  15.6  0.1016  39.6  0.052849  106.604
1501  5000  15.6  0.1016  39.6  0.052849  106.224
1502  6300  15.6  0.1016  39.6  0.052849  104.204

[1503 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       1503 non-null   int64  
 1   1       1503 non-null   float64
 2   2       1503 non-null   float64
 3   3       1503 non-null   float64
 4   4       1503 non-null   float64
 5   5       1503 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 70.6 KB


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
(X_train,X_test,y_train,y_test)=train_test_split(data,)
#data=train_test_split(X_test,X_train,Y_test,Y_train)


NameError: ignored

In [14]:
output=df[5].values

In [16]:
output

array([126.201, 125.201, 125.951, ..., 106.604, 106.224, 104.204])

In [17]:
data=df[[0,1,2,3,4]].values

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
model=LinearRegression()

In [23]:
(X_train,X_test,y_train,y_test)=train_test_split(data,output,test_size=0.33)

In [24]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
import matplotlib.pyplot as plt


In [27]:
model.score(X_train,y_train)

0.5222419279197021

In [28]:
model.score(X_test,y_test)

0.4952115183274333

In [30]:
predictions=model.predict(X_test)

In [31]:
predictions

array([130.54408986, 124.47599517, 121.36115754, 114.99060316,
       128.86748914, 134.37284599, 121.19007611, 132.11708418,
       126.33533077, 134.95957034, 121.5342264 , 125.11672746,
       121.1034419 , 128.10457478, 130.25377062, 119.3621757 ,
       128.62357859, 122.24834489, 123.24400783, 121.18713499,
       125.02637083, 121.61598748, 125.48894086, 129.63626026,
       130.20773147, 128.91412657, 128.17879782, 122.11895293,
       134.47574244, 122.49477796, 127.17838795, 115.42289747,
       122.84775182, 131.05086768, 121.63139408, 119.83468704,
       118.10260842, 123.89637509, 124.35550436, 122.06316603,
       122.50051884, 122.79620574, 126.40268437, 133.67266093,
       118.18197528, 125.06030701, 129.33972515, 129.55906264,
       119.43784822, 113.07979422, 123.68883129, 126.05380207,
       118.29039087, 126.55696729, 120.43601727, 127.44435753,
       130.05633058, 125.65330177, 125.71497112, 127.50805714,
       125.90175681, 122.35574761, 118.21302422, 120.61

NameError: ignored

In [40]:
from sklearn.ensemble import RandomForestRegressor

ValueError: ignored

In [41]:
model2=RandomForestRegressor()

In [42]:
model2.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [43]:
model2.score(X_train,y_train)

0.9889461624011339

In [44]:
model2.score(X_test,y_test)

0.9349262281591432

In [45]:
pred=model2.predict(X_train)

In [46]:
pred

array([127.18646, 120.26747, 133.34608, ..., 127.97662, 131.3527 ,
       119.21566])